# To make this work on your own repo, see PR #2
name: Docker Image CI - Main

on:
  push:
    branches:
      - main
    paths:
      - '/docker_build/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Lowercase Owner Name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          GHCR_REPO: ghcr.io/${{ env.OWNER_LC }}
          IMAGE_NAME: mcsli
          VERSION: 1.1.0
        with:
          context: ./docker_build
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.GHCR_REPO }}/${{ env.IMAGE_NAME }}:latest,${{ env.GHCR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
